name: alsadhan
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  flutter_staggered_grid_view: ^0.3.0
  flutter_paginator: ^0.0.6
  shared_preferences: ^0.5.6+3
  badges: ^1.1.1
  gson: ^0.1.4
  intl: ^0.16.0
  toast: ^0.1.5
  progress_dialog: ^1.2.1
  flutter_typeahead: ^1.8.0
  google_fonts: ^0.3.10
  flutter_spinkit: "^4.1.2"
  gradient_text: ^1.0.2
  rate_my_app: ^0.6.0+2
  flutter_icons: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  # ar images
   
    - images/ar_all_categories.jpg
    - images/ar_food_Beverages_ar.jpg
    - images/ar_fresh_food.jpg
    - images/ar_main_banner.jpg
    - images/ar_non_food_ar.jpg
   
    # ar sub
    - images/ar_bakery.jpg
    - images/ar_breakfast_ar.jpg
    - images/ar_electronics_ar.jpg
    - images/ar_fruits-vegetables_ar.jpg
    - images/ar_luggage_ar.jpg
    - images/ar_snacks_ar.jpg

    - images/right.png
    - images/non_food.jpg
    - images/others.jpg  
    - images/consumable_products.jpg
    - images/all_categories.jpg
    - images/others_new.jpg
   
    - images/non_food_new2.jpg
    - images/luggage.jpg
    - images/electronics.jpg
    - images/alsadanlogo.png
    - images/logo.png
    - images/sadhan_land.png
    - images/super_market.jpg 
    # - images/hot_deals.jpg 
    # - images/hot_deals_n.jpg
    - images/fruits_banner.png
    - images/main_banner.jpg
    # - images/splash_logo.jpg
    - images/Alsadhan_banner1.jpg
    - images/food-beverages-ar.jpg
    - images/fresh-food-ar.jpg
    - images/non-food-ar.jpg
  
  
# maincategory
    # - images/baby_care.jpg
    - images/fresh_food.jpg
    - images/frozen_food.jpg
    - images/health_beauty.jpg
    - images/healthy_liveing.jpg
    - images/household.jpg
    - images/super_market.jpg 
    - images/super_market_offer.jpg 
    - images/Alsadhan-logo.png
    # - images/pets.jpg

    # subcategory
    # - images/baby_care.jpg
    - images/food-beverages.jpg
    # - images/baby_food.jpg
    - images/bakery.jpg
    - images/breakfast.jpg
    # - images/cosmetics.jpg
    # - images/dairy.jpg
    # - images/grocery.jpg  
    - images/fruits_vegs.jpg 
    # - images/kitchen_shop.jpg
    # - images/laundry_detergent.jpg
    # - images/oil_ghees.jpg
    # - images/pets_accessories.jpg
    # - images/pets_food.jpg
    # - images/skin_care.jpg
    - images/snacks.jpg

    - images/new/fresh-vegitables.jpg
    - images/new/beverages.png
    - images/new/fresh-food.png
    - images/new/fruits-vegs.png
    - images/new/Main-banner-image.jpg
    - images/new/noon-food.png
    - images/new/search-icon.png
    - images/new/toggle-icon.png  
    - images/new/electronics.png
    - images/new/bakery.png
    - images/new/luggage.png 
    - images/new/snacks.png
    - images/new/breakfast.png
    - images/new/dairy.png
    - images/new/oil-ghee.png
    - images/new/wishlist.png
    - images/new/wishlisted.png
    - images/new/fresh-vegitables-ar.png

    - assets/locale/localization_en.json
    - assets/locale/localization_ar.json



    # - images/bakery.jpg
    # - images/fruits_vegs.jpg
    # - images/snacks.jpg
      # - images/oil_gees.jpg
     # - images/baby_care.jpg
     # - images/fresh_food.jpg     



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Helvetica
      fonts:
        - asset: fonts/helvetica/HelveticaNeue_Light.ttf
          weight: 200
        - asset: fonts/helvetica/HelveticaNeue_Regular.ttf
          weight: 400
        - asset: fonts/helvetica/HelveticaNeue_Medium.ttf
          weight: 500
        - asset: fonts/helvetica/HelveticaNeue-Bold.ttf
          weight: 700
        - asset: fonts/helvetica/HelveticaNeue_BlackCond.ttf
          weight: 900
  #